version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  play.catalog:
    image: ${DOCKER_REGISTRY-}playcatalog
    container_name: catalog
    build:
      context: .
      dockerfile: Play.Catalog\Dockerfile
    ports:
      - 5001:80
  play.inventory:
    image: ${DOCKER_REGISTRY-}playinventory
    container_name: inventory
    build:
      context: .
      dockerfile: Play.Inventory\Dockerfile
    ports:
      - 5005:80
volumes: 
  mongodbdata:
