version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  play.catalog:
    image: ${DOCKER_REGISTRY-}playcatalog
    container_name: catalog
    build:
      context: .
      dockerfile: Play.Catalog\Dockerfile
    ports:
      - 5001:80
  play.inventory:
    image: ${DOCKER_REGISTRY-}playinventory
    container_name: inventory
    build:
      context: .
      dockerfile: Play.Inventory\Dockerfile
    ports:
      - 5005:80
volumes:
  mongodbdata:
  rabbitmqdata: